### ISSUE TITLE
作者您好，我有几个关于这篇论文的小问题，希望您有空能够回答一下。

### ISSUE THREAD

**Issue by ZevineXu** [SleepThroughDifficulties/DSRM#3]
首先非常荣幸能够阅读到这么优秀一篇论文。非常具有启发性，但在阅读论文中，我有几个问题，希望您有空可以回答一下，万分感谢。
问题1：这个伪代码是如何和公式9对应起来的呢
问题2：我的理解是，在虚拟模型上更新一次之后，原来的样本便变成了扰动样本，因为他们在更新后的虚拟模型上会使得损失函数增大，然而在扰动函数后使用验证集数据进行求导就有点令我费解了，然后关于那个$\eta g$ 如果我没猜错那个$\eta g$是否表示原来论文中的$P_f^* -P0...|P_f^*$部分呢？这一部分比较难以理解，但感觉也是论文的关键点。
对占用您宝贵的时间感到抱歉，非常感谢。

**Comment by SleepThroughDifficulties** [comment]
同学您好，

感谢你对这个工作的兴趣。
你的理解大致上是正确的，只是中间可能有个比较绕的地方论文没有细讲。整个流程中我们不会涉及到对样本本身表示的扰动，而是想办法用一个上界去覆盖住对抗损失。


整个优化流程的本质在于我们需要搜索到一个新分布，他能在训练集（或者说输入的整个定义域）上给出更高的预测loss，从而覆盖住对抗损失。这个事情很自然地可以想到能够通过梯度上升来做，但问题在于这个梯度要回传到当前batch的输入样本权重而不是模型参数上，所以直接去做上升是没用的（我们期待的是整个分布上的loss上升而不是仅针对当前的这个batch）。所以需要先在一个虚拟模型上做一次梯度回传，这就相当于把与输入权重作为参数更新进模型参数里面了，那么下一次梯度上升的时候就可以链式法则求到验证集loss相对于这一次输入权重的梯度值。在实际的实现里用的是meta learning的框架，能够直接从第二次forward把梯度求回第一次的输入权重。

因此，公式9外部的梯度对应第二次反向传播过程，而内部的梯度对应最优的分布扰动方向，$P_f^* -P_0$是更新步长

一个有一点点类似（我觉得思路上可以相互借鉴）的推导是sharpness-aware minimization那篇文章（https://arxiv.org/abs/2010.01412），可以一并阅读作为参考。

**Comment by ZevineXu** [comment]
明白了！非常感谢大佬的回答！
